### ISSUE TITLE
Title shadow removing does not work

### ISSUE THREAD

**Issue by Hartulino** [PuckiSilver/NoShadow#10]
Title says it all, I am trying to use it for titles in 1.20.6 and it simply doesn't do anything.

**Comment by PuckiSilver** [comment]
Is your game modified in any way besides NoShadow?

**Comment by Hartulino** [comment]
Yes, I use mods like Sodium

**Comment by PuckiSilver** [comment]
Then I’m sorry but I can’t help, mods can change anything about the game and if they break vanilla shaders then that’s nothing I can fix. NoShadow is made to work with vanilla and it does work with a lot of mods but some mods simply use their own shaders - completely ignoring the vanilla shaders. Not in my power to fix.
