### ISSUE TITLE
Recent snapshots have broken the resource pack

### ISSUE THREAD

**Issue by IronFrite** [PuckiSilver/NoShadow#4]
In the newest snapshots the resource pack doesn't load anymore :c Maybe due to the modifications Mojang brought to shaders ?

**Comment by PuckiSilver** [comment]
Yes that is correct but I already released a changed version that works in the snapshot, you can find it in the other branch [here](https://github.com/PuckiSilver/NoShadow/tree/feat/mc-1.20.5) (notice the little `feat/mc-1.20.5` in the top left)

**Comment by IronFrite** [comment]
> Yes that is correct but I already released a changed version that works in the snapshot, you can find it in the other branch [here](https://github.com/PuckiSilver/NoShadow/tree/feat/mc-1.20.5) (notice the little `feat/mc-1.20.5` in the top left)

Oh perfect, I hadn't noticed that, thank you ! 🙌
