### ISSUE TITLE
1.20.5 Shader Changes

### ISSUE THREAD

**Issue by IvanTG1563** [PuckiSilver/NoShadow#5]
Due to the shader changes in the last snapshots this doesn't work, is a fix planned?

**Comment by PuckiSilver** [comment]
Check out this issue https://github.com/PuckiSilver/NoShadow/issues/4 or directly the update branch

**Comment by IvanTG1563** [comment]
Thanks! And sorry, I'm not much used to Github so i couldnt find the closed issues

**Comment by PuckiSilver** [comment]
No problem, you found it now - it should really state that in the readme until 1.20.5 comes out

Edit: I added a notice to the readme
